name: cancer_monitor
description: Anticancer treatment record monitoring mobile app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.5.0
  cloud_functions: ^6.3.2
  crypto: ^3.0.7
  firebase_app_check: ^0.4.4+2
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.1.0
  google_sign_in: ^7.2.0
  health: ^13.3.1
  permission_handler: ^12.0.3
  shared_preferences: ^2.5.5
  sign_in_with_apple: ^8.1.0
  timezone: ^0.11.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
