// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKON6370EHDKwV6ew9PihWyCK-Dql5r0',
    appId: '1:210055151747:android:7a79ec2ada7e7310e49bb6',
    messagingSenderId: '210055151747',
    projectId: 'cancer-monitor-f40ab',
    storageBucket: 'cancer-monitor-f40ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCru-FYDgbzWybXCv-MqUqOIQBjA4kSurw',
    appId: '1:210055151747:ios:16d21204de8a429be49bb6',
    messagingSenderId: '210055151747',
    projectId: 'cancer-monitor-f40ab',
    storageBucket: 'cancer-monitor-f40ab.firebasestorage.app',
    iosClientId:
        '210055151747-ap0ac39o8mjog7akg6vitfcse9sjvbtg.apps.googleusercontent.com',
    iosBundleId: 'com.nanimi74.cancermonitor',
  );
}
